### ISSUE TITLE
No module named 'pyrvt'

### ISSUE THREAD

**Issue by geoweaser** [arkottke/pystrata#20]
Hello, I just installled pystrata and when running the first example as a jupyter threw teh following error, suggesting the pyrvt module is missing. I installed all the dependencies listed (cmake, qt, gsl, qwt, and fftw). How can I fix this?

`import matplotlib.pyplot as plt
import numpy as np

import pystrata

%matplotlib inline

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[7], line 4
      1 import matplotlib.pyplot as plt
      2 import numpy as np
----> 4 import pystrata
      6 get_ipython().run_line_magic('matplotlib', 'inline')

File ~\Anaconda3\envs\pystrata\Lib\site-packages\pystrata\__init__.py:23
      1 # -*- coding: utf-8 -*-
      2 # The MIT License (MIT)
      3 #
   (...)
     21 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
     22 # SOFTWARE.
---> 23 from . import motion
     24 from . import output
     25 from . import propagation

File ~\Anaconda3\envs\pystrata\Lib\site-packages\pystrata\motion.py:27
     24 import re
     26 import numpy as np
---> 27 import pyrvt
     28 from scipy.constants import g as GRAVITY
     30 # Gravity in m/sec²

ModuleNotFoundError: No module named 'pyrvt'`

**Comment by geoweaser** [comment]
I seemed to have fixed the problem. There were many dependencies that needed to be installed:
`conda install --yes setuptools numpy scipy matplotlib numba openpyxl xlrd xlwt pip
pip install pyrvt
pip install pyexcel
pip install pykooh
pip install tomli
pip install tomli`

**Comment by arkottke** [comment]
Glad to hear you got it fixed. I will adjust the packing so that the
dependences are install automatically.
