### ISSUE TITLE
problems with pystrata.site._load_published_curves()

### ISSUE THREAD

**Issue by geoweaser** [arkottke/pystrata#21]
Hi, I am working through some of the examples and came across a problem with example 15. Here's what I ran:
```
import pystrata

pystrata.site._load_published_curves()
```
And this is what was returned:
```
Traceback (most recent call last):
  File "P:\Projects\Seismic\SHA\JPR_scenario\ReelfootFault\pySTRATA\bin\nonlinear_work.py", line 3, in <module>
    pystrata.site._load_published_curves()
  File "C:\Users\nvca223\Anaconda3\envs\pystrata\Lib\site-packages\pystrata\site.py", line 56, in _load_published_curves
    models = tomli.load(fp)["models"]
             ^^^^^^^^^^^^^^
  File "C:\Users\nvca223\Anaconda3\envs\pystrata\Lib\site-packages\tomli\_parser.py", line 66, in load
    return loads(s, parse_float=parse_float)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nvca223\Anaconda3\envs\pystrata\Lib\site-packages\tomli\_parser.py", line 116, in loads
    raise suffixed_err(src, pos, "Invalid statement")
tomli.TOMLDecodeError: Invalid statement (at line 1, column 1)
```
The published_curves.toml file was not apparently included in my original download, so I downloaded it from github and installed it at ...\Anaconda3\envs\pystrata\Lib\site-packages\pystrata\data. I had to create the "data" folder shown in that path.

I would appreciate any help sorting out this issue.

**Comment by arkottke** [comment]
Thanks for reporting this issue. The data files weren't included in the package manifest. I will fix it.

**Comment by geoweaser** [comment]
Thank you. However, I still have a problem even when I installed the file in the data folder. Apparently the tomli.TOMLDecodeError cannot parse it.

**Comment by arkottke** [comment]
You probably need to install tomli with "pip install tomli", which is now a
dependency.

**Comment by geoweaser** [comment]
I'm not sure, but it seems like the dependency should be satisfied with my installation? The last two error messages I posted imply tomli is available, as I think does the following:
```
(base) C:\Users\nvca223>activate pystrata

(pystrata) C:\Users\nvca223>pip install tomli
Requirement already satisfied: tomli in c:\users\nvca223\anaconda3\envs\pystrata\lib\site-packages (2.0.1)
```

**Comment by arkottke** [comment]
I suspect you might not have downloaded the raw version of the
published_curves.toml
file. If you could update pystrata with pip: pip install --upgrade pystrata
. V0.5.3 should have the required toml file included.

**Comment by geoweaser** [comment]
Thank you! That fixed the problem for me.
